# Twitter
CONSUMER_KEY='YOUR-CONSUMER_KEY'
CONSUMER_SECRET='YOUR-CONSUMER_SECRET'
BEARER_TOKEN='YOUR-BEARER_TOKEN'
ACCESS_TOKEN='YOUR-ACCESS_TOKEN'
ACCESS_TOKEN_SECRET='YOUR-ACCESS_TOKEN_SECRET'
CLIENT_ID='YOUR-CLIENT_ID'
CLIENT_SECRET='YOUR-CLIENT_SECRET'

# Telegram
CHAT_ID='YOUR-CHAT_ID'
TOKEN_TELEGRAM='YOUR-TOKEN_TELEGRAM'
